In [234]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import pickle
import joblib

from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.model_selection import GridSearchCV

In [235]:
diamonds = pd.read_csv('./data/diamondsql.csv')
diamonds['volume'] = (4/3) * np.pi * diamonds['x'] * diamonds['y'] * diamonds['z']
diamonds['length_width_ratio'] = diamonds['x'] / diamonds['y']
diamonds['width_depth_ratio'] = diamonds['y'] / diamonds['z']
diamonds

,index_id,price,city_id,carat,city_id.1,city,index_id.1,cut_id,color_id,clarity_id,...,color,index_id.2,depth,table,x,y,z,volume,length_width_ratio,width_depth_ratio
0,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,4268,6c425048aa7badd9d84615bd8620ca1864efd81cfdb69d...,1.21,6c425048aa7badd9d84615bd8620ca1864efd81cfdb69d...,Dubai,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,de88c121a82a06352bf1aaceba20578356408a334ba046...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,...,J,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,62.4,58.0,6.83,6.79,4.25,825.596831,1.005891,1.597647
1,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,505,89c7286890f7347ab235234e74d406596a127ae3679042...,0.32,89c7286890f7347ab235234e74d406596a127ae3679042...,Kimberly,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,388655e25e91872329272fc10128ef5354b3b19a05d7e8...,44bd7ae60f478fae1061e11a7739f4b94d1daf917982d3...,f0b2a1d0db08cc64f85d74f1d15c2191e0e49039f4d8f2...,...,H,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,63.0,57.0,4.35,4.38,2.75,219.474804,0.993151,1.592727
2,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,2686,2bd25cd960aba8b706e2b67f2bb38b750ee5384b0e9883...,0.71,2bd25cd960aba8b706e2b67f2bb38b750ee5384b0e9883...,Las Vegas,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,f7b19afcde965ea4942b878d266f89f8ba9a5a833e60f7...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...,...,G,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,65.5,55.0,5.62,5.53,3.65,475.163334,1.016275,1.515068
3,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,738,89c7286890f7347ab235234e74d406596a127ae3679042...,0.41,89c7286890f7347ab235234e74d406596a127ae3679042...,Kimberly,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,c939327ca16dcf97ca32521d8b834bf1de16573d21deda...,3f39d5c348e5b79d06e842c114e6cc571583bbf44e4b0e...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...,...,D,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,63.8,56.0,4.68,4.72,3.00,277.586100,0.991525,1.573333
4,4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328c...,4882,6c425048aa7badd9d84615bd8620ca1864efd81cfdb69d...,1.02,6c425048aa7badd9d84615bd8620ca1864efd81cfdb69d...,Dubai,4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328c...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...,...,G,4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328c...,60.5,59.0,6.55,6.51,3.95,705.517829,1.006144,1.648101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,f0bc79169405ebeb24e308055156b946ffd819db9b4f75...,10070,ca3aa21a5b70c3e88cc6336682c8c7da928a0c66a5ead4...,1.34,ca3aa21a5b70c3e88cc6336682c8c7da928a0c66a5ead4...,Antwerp,f0bc79169405ebeb24e308055156b946ffd819db9b4f75...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,333e0a1e27815d0ceee55c473fe3dc93d56c63e3bee2b3...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...,...,G,f0bc79169405ebeb24e308055156b946ffd819db9b4f75...,62.7,57.0,7.10,7.04,4.43,927.520129,1.008523,1.589165
40451,339916a23bf22b052b54cb2a9b36ee8418c1c68b46acad...,12615,e9c722cbefc2f055ae60b4e2cbe73a2d99537eab0c37f3...,2.02,e9c722cbefc2f055ae60b4e2cbe73a2d99537eab0c37f3...,Madrid,339916a23bf22b052b54cb2a9b36ee8418c1c68b46acad...,c939327ca16dcf97ca32521d8b834bf1de16573d21deda...,f67ab10ad4e4c53121b6a5fe4da9c10ddee905b978d378...,03c358cbd92e83278fd523f58dc6a9b4b198d00728af65...,...,F,339916a23bf22b052b54cb2a9b36ee8418c1c68b46acad...,57.1,60.0,8.31,8.25,4.73,1358.328217,1.007273,1.744186
40452,46957922b99954654c1deb8d854c3f069bf118b2ce9415...,5457,89c7286890f7347ab235234e74d406596a127ae3679042...,1.01,89c7286890f7347ab235234e74d406596a127ae3679042...,Kimberly,46957922b99954654c1deb8d854c3f069bf118b2ce9415...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,44bd7ae60f478fae1061e11a7739f4b94d1daf917982d3...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...,...,H,46957922b99954654c1deb8d854c3f069bf118b2ce9415...,62.7,56.0,6.37,6.42,4.01,686.922026,0.992212,1.600998
40453,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,456,89c7286890f7347ab235234e74d406596a127ae3679042...,0.33,89c7286890f7347ab235234e74d406596a127ae3679042...,Kimberly,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,6da43b944e494e885e69af021f93c6d9331c78aa228084...,ef736c1f91cd1900c3d9cde925b1bf4f013adc0211a9ee...,...,J,9d733392d362d5c6f1d9b9659b601c7d4b5a1c1c8df579...,61.9,54.3,4.45,4.47,2.76,229.966844,0.995526,1.619565
40454,a02744a70faa594d240b067f21fcc23a8d17cd1098a9fb...,6232,ecc0e7dc084f141b29479058967d0bc07dee25d9690a98...,1.24,ecc0e7dc084f141b29479058967d0bc07dee25d9690a98...,London,a02744a70faa594d240b067f21fcc23a8d17cd1098a9fb...,4e3cfaa334cbafb57a399a98fad8d3812ece460018f457...,a83dd0ccbffe39d071cc317ddf6e97f5c6b1c87af91919...,bd4f4a250da88f87729febc739ae97f439a14f9d38f0e3...,...,I,a02744a70faa594d240b067f21fcc23a8d17cd1098a9fb...,62.0,58.0,6.83,6.88,4.25,836.539941,0.992733,1.618824

In [236]:
diamonds.columns

Index(['index_id', 'price', 'city_id', 'carat', 'city_id.1', 'city',
       'index_id.1', 'cut_id', 'color_id', 'clarity_id', 'cut_id.1', 'cut',
       'clarity_id.1', 'clarity', 'color_id.1', 'color', 'index_id.2', 'depth',
       'table', 'x', 'y', 'z', 'volume', 'length_width_ratio',
       'width_depth_ratio'],
      dtype='object')

In [237]:
diamonds = diamonds.drop(['index_id', 'city_id', 'city_id.1','index_id.1','cut_id', 'color_id', 'clarity_id', 'cut_id.1', 'clarity_id.1', 'color_id.1', 'index_id.2'], axis = 1)

In [238]:
diamonds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40455 entries, 0 to 40454
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   price               40455 non-null  int64
 1   carat               40455 non-null  float64
 2   city                40455 non-null  object
 3   cut                 40455 non-null  object
 4   clarity             40455 non-null  object
 5   color               40455 non-null  object
 6   depth               40455 non-null  float64
 7   table               40455 non-null  float64
 8   x                   40455 non-null  float64
 9   y                   40455 non-null  float64
 10  z                   40455 non-null  float64
 11  volume              40455 non-null  float64
 12  length_width_ratio  40451 non-null  float64
 13  width_depth_ratio   40451 non-null  float64
dtypes: float64(9), int64(1), object(4)
memory usage: 4.3+ MB

In [239]:
# Identificamos las columnas que tienen valores nulos
columns_with_missing_values = diamonds.columns[diamonds.isnull().any()]

# Para cada columna con valores nulos, imputamos con el valor más frecuente en caso de ser categórica
for column in columns_with_missing_values:
    if diamonds[column].dtype == 'object':
        # Si la columna es de tipo objeto (categórica), imputamos con el valor más frecuente
        most_frequent_value = diamonds[column].mode()[0]
        diamonds[column].fillna(most_frequent_value, inplace=True)
    else:
        # Si la columna es numérica, imputamos con la media o la mediana
        diamonds[column].fillna(diamonds[column].mean(), inplace=True)  

# Verificamos que ya no hay valores nulos
#print(diamonds.isnull().sum())
diamonds

,price,carat,city,cut,clarity,color,depth,table,x,y,z,volume,length_width_ratio,width_depth_ratio
0,4268,1.21,Dubai,Premium,VS2,J,62.4,58.0,6.83,6.79,4.25,825.596831,1.005891,1.597647
1,505,0.32,Kimberly,Very Good,VS2,H,63.0,57.0,4.35,4.38,2.75,219.474804,0.993151,1.592727
2,2686,0.71,Las Vegas,Fair,VS1,G,65.5,55.0,5.62,5.53,3.65,475.163334,1.016275,1.515068
3,738,0.41,Kimberly,Good,SI1,D,63.8,56.0,4.68,4.72,3.00,277.586100,0.991525,1.573333
4,4882,1.02,Dubai,Ideal,SI1,G,60.5,59.0,6.55,6.51,3.95,705.517829,1.006144,1.648101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,10070,1.34,Antwerp,Ideal,VS1,G,62.7,57.0,7.10,7.04,4.43,927.520129,1.008523,1.589165
40451,12615,2.02,Madrid,Good,SI2,F,57.1,60.0,8.31,8.25,4.73,1358.328217,1.007273,1.744186
40452,5457,1.01,Kimberly,Ideal,SI1,H,62.7,56.0,6.37,6.42,4.01,686.922026,0.992212,1.600998
40453,456,0.33,Kimberly,Ideal,VS1,J,61.9,54.3,4.45,4.47,2.76,229.966844,0.995526,1.619565
40454,6232,1.24,London,Ideal,SI1,I,62.0,58.0,6.83,6.88,4.25,836.539941,0.992733,1.618824

In [240]:
mean_volume = diamonds['volume'].mean()
diamonds['relative_volume'] = diamonds['volume'] / mean_volume
#diamonds['density'] = diamonds['carat'] / diamonds['volume']
diamonds['dimension_difference'] = diamonds['x'] - diamonds['y']
quality_weights = {
    'cut': {'Fair': 0.2, 'Good': 0.4, 'Very Good': 0.6, 'Premium': 0.8, 'Ideal': 1.0},
    'clarity': {'I1': 0.2, 'SI2': 0.4, 'SI1': 0.6, 'VS2': 0.8, 'VS1': 1.0},
    'color': {'J': 0.2, 'I': 0.4, 'H': 0.6, 'G': 0.8, 'F': 1.0}
}
diamonds['quality_index'] = diamonds['cut'].map(quality_weights['cut']) * diamonds['clarity'].map(quality_weights['clarity']) * diamonds['color'].map(quality_weights['color'])

In [241]:
diamonds_encoded = pd.get_dummies(diamonds, columns=['city','cut','clarity','color'])

In [242]:
diamonds_encoded

,price,carat,depth,table,x,y,z,volume,length_width_ratio,width_depth_ratio,...,clarity_VS2,clarity_VVS1,clarity_VVS2,color_D,color_E,color_F,color_G,color_H,color_I,color_J
0,4268,1.21,62.4,58.0,6.83,6.79,4.25,825.596831,1.005891,1.597647,...,True,False,False,False,False,False,False,False,False,True
1,505,0.32,63.0,57.0,4.35,4.38,2.75,219.474804,0.993151,1.592727,...,True,False,False,False,False,False,False,True,False,False
2,2686,0.71,65.5,55.0,5.62,5.53,3.65,475.163334,1.016275,1.515068,...,False,False,False,False,False,False,True,False,False,False
3,738,0.41,63.8,56.0,4.68,4.72,3.00,277.586100,0.991525,1.573333,...,False,False,False,True,False,False,False,False,False,False
4,4882,1.02,60.5,59.0,6.55,6.51,3.95,705.517829,1.006144,1.648101,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,10070,1.34,62.7,57.0,7.10,7.04,4.43,927.520129,1.008523,1.589165,...,False,False,False,False,False,False,True,False,False,False
40451,12615,2.02,57.1,60.0,8.31,8.25,4.73,1358.328217,1.007273,1.744186,...,False,False,False,False,False,True,False,False,False,False
40452,5457,1.01,62.7,56.0,6.37,6.42,4.01,686.922026,0.992212,1.600998,...,False,False,False,False,False,False,False,True,False,False
40453,456,0.33,61.9,54.3,4.45,4.47,2.76,229.966844,0.995526,1.619565,...,False,False,False,False,False,False,False,False,False,True
40454,6232,1.24,62.0,58.0,6.83,6.88,4.25,836.539941,0.992733,1.618824,...,False,False,False,False,False,False,False,False,True,False

In [243]:
X = diamonds_encoded.drop('price', axis=1)
y = diamonds_encoded['price']

In [244]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"X_train: {X_train.shape}, X_test: {X_test.shape}, y_train: {y_train.shape}, y_test: {y_test.shape}")

X_train: (32364, 45), X_test: (8091, 45), y_train: (32364,), y_test: (8091,)

In [245]:
model_xgb = XGBRegressor(colsample_bytree = 0.95,
                          gamma = 0.14,
                          learning_rate = 0.012,
                          max_depth = 7,
                          missing = np.inf,
                          n_estimators = 1130,
                          subsample = 0.8, 
                         objective='reg:squarederror', random_state=42)

model_xgb.fit(X_train, y_train)

y_pred = model_xgb.predict(X_test)

In [246]:
mean_squared_error(y_test, y_pred)

292725.24710136885

In [247]:
rmse = mean_squared_error(y_test, y_pred, squared=False)
rmse

541.0408922635783

In [248]:
diamonds_test = pd.read_csv('./data/diamonds_test.csv')
diamonds_test['volume'] = (4/3) * np.pi * diamonds_test['x'] * diamonds_test['y'] * diamonds_test['z']
diamonds_test['length_width_ratio'] = diamonds_test['x'] / diamonds_test['y']
diamonds_test['width_depth_ratio'] = diamonds_test['y'] / diamonds_test['z']
diamonds_test
mean_volume = diamonds_test['volume'].mean()
diamonds_test['relative_volume'] = diamonds_test['volume'] / mean_volume
#diamonds['density'] = diamonds['carat'] / diamonds['volume']
diamonds_test['dimension_difference'] = diamonds_test['x'] - diamonds_test['y']
quality_weights = {
    'cut': {'Fair': 0.2, 'Good': 0.4, 'Very Good': 0.6, 'Premium': 0.8, 'Ideal': 1.0},
    'clarity': {'I1': 0.2, 'SI2': 0.4, 'SI1': 0.6, 'VS2': 0.8, 'VS1': 1.0},
    'color': {'J': 0.2, 'I': 0.4, 'H': 0.6, 'G': 0.8, 'F': 1.0}
}
diamonds_test['quality_index'] = diamonds_test['cut'].map(quality_weights['cut']) * diamonds_test['clarity'].map(quality_weights['clarity']) * diamonds_test['color'].map(quality_weights['color'])

In [249]:
#diamonds_test=diamonds_test.drop('city',axis=1)

In [250]:
diamonds_encoded_test = pd.get_dummies(diamonds_test, columns=['city','cut','clarity','color'])
diamonds_encoded_test

,id,carat,depth,table,x,y,z,volume,length_width_ratio,width_depth_ratio,...,clarity_VS2,clarity_VVS1,clarity_VVS2,color_D,color_E,color_F,color_G,color_H,color_I,color_J
0,0,0.79,62.7,60.0,5.82,5.89,3.67,526.978568,0.988115,1.604905,...,False,False,False,False,False,True,False,False,False,False
1,1,1.20,61.0,57.0,6.81,6.89,4.18,821.544750,0.988389,1.648325,...,False,False,False,False,False,False,False,False,False,True
2,2,1.57,62.2,61.0,7.38,7.32,4.57,1034.123131,1.008197,1.601751,...,False,False,False,False,False,False,False,True,False,False
3,3,0.90,63.8,54.0,6.09,6.13,3.90,609.861171,0.993475,1.571795,...,False,False,False,False,False,True,False,False,False,False
4,4,0.50,62.9,58.0,5.05,5.09,3.19,343.469717,0.992141,1.595611,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,13480,0.57,61.9,56.0,5.35,5.32,3.30,393.430444,1.005639,1.612121,...,False,False,False,False,True,False,False,False,False,False
13481,13481,0.71,62.2,55.0,5.71,5.73,3.56,487.898337,0.996510,1.609551,...,True,False,False,False,False,False,False,False,True,False
13482,13482,0.70,61.6,55.0,5.75,5.71,3.53,485.475444,1.007005,1.617564,...,False,False,False,False,False,True,False,False,False,False
13483,13483,0.70,58.8,57.0,5.85,5.89,3.45,497.942121,0.993209,1.707246,...,False,False,False,False,False,True,False,False,False,False
13484,13484,0.40,62.4,55.0,4.70,4.73,2.94,273.775725,0.993658,1.608844,...,False,False,True,False,False,False,False,False,True,False

In [251]:
X_prueba = diamonds_encoded_test.drop('id', axis=1)

In [252]:
y_prueba = model_xgb.predict(X_prueba)

In [253]:
y_prueba

array([2843.0356 , 5552.7554 , 9498.668  , ..., 3082.2905 , 2145.148  ,
        815.43445], dtype=float32)

In [254]:
solution = []
for i, value in enumerate(y_prueba):
    solution.append((i,value))

In [255]:
solution_df = pd.DataFrame(solution)

In [256]:
solution_df.columns = ['id', 'price']

In [257]:
solution_df['price'].to_csv('solution.csv')